name: Github Actions

on: push
jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      # Клонируем репозиторий
      - uses: actions/checkout@v3
      # Устанавливаем Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm' # ускоряет повторные сборки
      # Ставим зависимости
      - name: run install
        run: make install

      - name: run lint 
        run: make lint

      - name: run tests
        run: make test 

        - name: Test & publish code coverage
        # Publish code coverage on Code Climate
        # https://github.com/paambaati/codeclimate-action
        uses: paambaati/codeclimate-action@v2.7.4
        # Add Code Climate secret key
        env:
          CC_TEST_REPORTER_ID: acc21f172d4df284fe99e3255ba3d8190722d2b3fe28d32e7ebf8e17a46d0ac3
        with:
          coverageCommand: make test-coverage
          debug: true
